version: '3'

services:
  document-classification:
    build: ./
    ports:
      - "8501:8501"
    image: pytorch_doc_ocr_classification_deploy:latest
    tty: true
    stdin_open: true
    command: sh
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ../../src:/home
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]