version: '3'

services:
  document-classification:
    build: ./
    image: pytorch_doc_ocr_classification:latest
    ports:
      - "8888:8888"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ../notebooks:/home
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]